#!/bin/bash
#SBATCH --job-name=L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1          # Name of the job
#SBATCH --time=7-00:00:00               # Allocation time
#SBATCH --mem-per-cpu=2000              # Memory per allocated cpu
#SBATCH --nodes=2               # Number of nodes
#SBATCH --ntasks=64
#SBATCH --output=/home/x_ilama/FFLO/Output_FFLO/dx_2pi_8_dy_2pi_8/L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1/logs/log_L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1.o
#SBATCH --error=/home/x_ilama/FFLO/Output_FFLO/dx_2pi_8_dy_2pi_8/L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1/logs/log_L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1.e

srun ../build/Release/FFLO 128 /home/x_ilama/FFLO/Output_FFLO/dx_2pi_8_dy_2pi_8/L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1 /home/x_ilama/FFLO/Output_FFLO/dx_2pi_8_dy_2pi_8/L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1 0 &> /home/x_ilama/FFLO/Output_FFLO/dx_2pi_8_dy_2pi_8/L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1/logs/log_L128_dx_2pi_8_dy_2pi_8_bmin0.1_bmax4.0_init1.o


